import React, { useState, useCallback } from 'react';
import { GeneratedLevel, Difficulty, SegmentType } from './types';
import { generateLevelDesign } from './services/geminiService';
import { buildLevelData, wrapInGMD } from './utils/gdBuilder';
import { LevelPreview } from './components/LevelPreview';
import { GoogleGenAI } from '@google/genai';

const App: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [level, setLevel] = useState<GeneratedLevel | null>(null);
  
  // Form State
  const [difficulty, setDifficulty] = useState<Difficulty>(Difficulty.NORMAL);
  const [theme, setTheme] = useState("Standard geometry dash flow with clear jumps");
  const [levelName, setLevelName] = useState("AI Gen Level");

  const [hasKey, setHasKey] = useState(!!process.env.API_KEY);

  const handleGenerate = async () => {
    if (!hasKey && !process.env.API_KEY) {
       alert("No API Key detected. This app requires a configured environment variable.");
       return;
    }
    
    setLoading(true);
    setLevel(null);

    try {
      const segments = await generateLevelDesign(difficulty, theme);
      
      const rawData = buildLevelData(segments, levelName);
      
      setLevel({
        name: levelName,
        description: `A ${difficulty} level generated by AI.`,
        data: rawData,
        segments: segments
      });
    } catch (e) {
      console.error(e);
      alert("Failed to generate level. Check console for details.");
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!level) return;
    
    const gmdContent = wrapInGMD(level.data, level.name);
    const blob = new Blob([gmdContent], { type: 'text/xml' }); // .gmd is often treated as XML or text
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${level.name.replace(/\s+/g, '_')}.gmd`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyString = () => {
      if(!level) return;
      navigator.clipboard.writeText(level.data);
      alert("Raw level string copied to clipboard! You can paste this into tools or save files.");
  };

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex flex-col items-center p-4 md:p-8">
      
      {/* Header */}
      <header className="max-w-4xl w-full mb-8 flex justify-between items-center border-b border-slate-700 pb-4">
        <div>
           <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-500">
             GD LevelGen AI
           </h1>
           <p className="text-slate-400 text-sm mt-1">
             Generate .gmd files for Geometry Dash using Gemini
           </p>
        </div>
        <div className="flex items-center gap-2">
           <span className={`w-3 h-3 rounded-full ${hasKey ? 'bg-green-500' : 'bg-red-500'}`}></span>
           <span className="text-xs text-slate-400">{hasKey ? 'API Ready' : 'No API Key'}</span>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl w-full grid grid-cols-1 md:grid-cols-3 gap-8">
        
        {/* Controls */}
        <div className="md:col-span-1 bg-slate-800 p-6 rounded-xl border border-slate-700 h-fit sticky top-8">
          <h2 className="text-xl font-semibold mb-6 flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
            </svg>
            Configuration
          </h2>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-slate-400 mb-1">Level Name</label>
              <input 
                type="text" 
                value={levelName}
                onChange={(e) => setLevelName(e.target.value)}
                className="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 text-sm focus:border-blue-500 focus:outline-none transition-colors"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-400 mb-1">Difficulty</label>
              <select 
                value={difficulty}
                onChange={(e) => setDifficulty(e.target.value as Difficulty)}
                className="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 text-sm focus:border-blue-500 focus:outline-none transition-colors"
              >
                {Object.values(Difficulty).map(d => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-400 mb-1">Prompt / Style</label>
              <textarea 
                value={theme}
                onChange={(e) => setTheme(e.target.value)}
                rows={3}
                className="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 text-sm focus:border-blue-500 focus:outline-none transition-colors resize-none"
                placeholder="e.g. Fast paced ship gameplay..."
              />
            </div>

            <button 
              onClick={handleGenerate}
              disabled={loading}
              className={`w-full py-3 rounded font-bold text-white shadow-lg transition-all
                ${loading 
                  ? 'bg-slate-600 cursor-not-allowed' 
                  : 'bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 active:scale-95'
                }`}
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                   <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                     <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                     <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                   </svg>
                   Generating...
                </span>
              ) : 'Generate Level'}
            </button>
          </div>
        </div>

        {/* Output */}
        <div className="md:col-span-2 space-y-6">
          
          {level ? (
            <div className="bg-slate-800 p-6 rounded-xl border border-slate-700 animate-fade-in">
              <div className="flex justify-between items-start mb-4">
                 <div>
                    <h2 className="text-2xl font-bold text-white">{level.name}</h2>
                    <p className="text-slate-400 text-sm">{level.description}</p>
                 </div>
                 <span className="px-3 py-1 rounded-full bg-blue-900/50 text-blue-300 text-xs border border-blue-700/50">
                    {level.segments.length} Segments
                 </span>
              </div>

              {/* Visualization */}
              <div className="mb-6">
                 <h3 className="text-sm font-semibold text-slate-300 mb-2">Layout Preview</h3>
                 <LevelPreview segments={level.segments} />
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-2 gap-4">
                 <button 
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-2 bg-slate-700 hover:bg-slate-600 text-white py-3 rounded transition-colors border border-slate-600"
                 >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download .gmd
                 </button>
                 <button 
                    onClick={handleCopyString}
                    className="flex items-center justify-center gap-2 bg-slate-700 hover:bg-slate-600 text-white py-3 rounded transition-colors border border-slate-600"
                 >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                    </svg>
                    Copy Raw String
                 </button>
              </div>
              <p className="mt-4 text-xs text-slate-500 text-center">
                 To use in GDShare: Download the .gmd file and import. 
                 <br/>
                 To use in Mega Hack/Other Tools: Copy Raw String and paste from clipboard.
              </p>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center bg-slate-800/50 rounded-xl border-2 border-dashed border-slate-700 p-12 text-center text-slate-500">
               {!loading && (
                 <>
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mb-4 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                  </svg>
                  <p className="text-lg">Ready to build.</p>
                  <p className="text-sm">Configure options on the left and click Generate.</p>
                 </>
               )}
               {loading && (
                 <p className="animate-pulse">AI is constructing level geometry...</p>
               )}
            </div>
          )}

          {/* Prompt History / Debug (Optional, kept minimal) */}
          {level && (
            <div className="bg-slate-800 p-4 rounded-xl border border-slate-700">
               <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Segment Data (Debug)</h3>
               <div className="flex flex-wrap gap-2">
                 {level.segments.map((seg, i) => (
                   <span key={i} className="text-xs bg-slate-900 border border-slate-700 px-2 py-1 rounded text-slate-300">
                     {seg.type}
                   </span>
                 ))}
               </div>
            </div>
          )}

        </div>
      </main>
    </div>
  );
};

export default App;
